n = int(input("Escolha uma numero pra saber a sua tabuada \n"))
print("-" * 10)
print("{} * {:2} = {} ".format(n, 1, n * 1))
print("{} * {:2} = {} ".format(n, 2, n * 1))
print("{} * {:2} = {} ".format(n, 3, n * 1))
print("{} * {:2} = {} ".format(n, 4, n * 1))
print("{} * {:2} = {} ".format(n, 5, n * 1))
print("{} * {:2} = {} ".format(n, 6, n * 1))
print("{} * {:2} = {} ".format(n, 7, n * 1))
print("{} * {:2} = {} ".format(n, 8, n * 1))
print("{} * {:2} = {} ".format(n, 9, n * 1))
print("{} * {} = {} ".format(n, 0, n * 1))
print("-" * 10)
